package com.github.edgger.alfabattle.task4.exception;

public class PersonNotFoundException extends RuntimeException {
}
