package com.github.edgger.alfabattle.task2.exceptions;

public class UserNotFoundException extends RuntimeException{
}
